spring:
  application:
    name: apigateway

server:
  port: 9090

eureka:
  instance:
    hostname: apigateway
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cms-realm

spring:
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/userservice/**
          filters:
            - StripPrefix=1

        - id: courseservice
          uri: lb://courseservice
          predicates:
            - Path=/courseservice/**
          filters:
            - StripPrefix=1

        - id: notificationservice
          uri: lb://notificationservice
          predicates:
            - Path=/notificationservice/**
          filters:
            - StripPrefix=1

        - id: userassessmentservice
          uri: lb://userassessmentservice
          predicates:
            - Path=/userassessmentservice/**
          filters:
            - StripPrefix=1

        - id: analyticsservice
          uri: lb://analyticsservice
          predicates:
            - Path=/analyticsservice/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
