spring:
  application:
    name: cloakresourceserver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cms-realm

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8090

eureka:
  instance:
    hostname: cloakresourceserver
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:4200"

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
