spring:
  application:
    name: cloak-resource-server

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: when_authorized

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cms-realm

spring:
  cloud:
    compatibility-verifier:
      enabled: false

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:4200
