# --- Cloak Resource Server Configuration (K8s) ---

server:
  port: 8080

spring:
  application:
    name: cloakresourceserver

  # SPRING SECURITY - OAUTH2 RESOURCE SERVER
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cms-realm

  cloud:
    compatibility-verifier:
      enabled: false

# ----------------------------------------------------
# EUREKA CLIENT CONFIGURATION (Kubernetes DNS)
# ----------------------------------------------------
eureka:
  instance:
    hostname: cloakresourceserver
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver.cms.svc.cluster.local:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# ----------------------------------------------------
# ACTUATOR (HEALTH CHECK) CONFIGURATION
# ----------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: when_authorized

# ----------------------------------------------------
# CORS CONFIGURATION
# ----------------------------------------------------
app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:4200"

# ----------------------------------------------------
# LOGGING CONFIGURATION
# ----------------------------------------------------
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
