# cms-secrets-public.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cms-secrets
  namespace: cms
type: Opaque
stringData:
  DB_USERNAME: "root"
  DB_PASSWORD: ""   # left empty for public repos

  DB_URL_USER: "jdbc:mysql://mysql.cms.svc.cluster.local:3306/user_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8"
  DB_URL_COURSE: "jdbc:mysql://mysql.cms.svc.cluster.local:3306/course_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8"
  DB_URL_NOTIFICATION: "jdbc:mysql://mysql.cms.svc.cluster.local:3306/notification_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8"
  DB_URL_ANALYTICS: "jdbc:mysql://mysql.cms.svc.cluster.local:3306/analytics_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8"
  DB_URL_ASSESSMENT: "jdbc:mysql://mysql.cms.svc.cluster.local:3306/userassessment_service_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8"

  CONFIG_GIT_URI: "https://github.com/simongawar/CMS-Project-config.git"
  CONFIG_GIT_USERNAME: "simongawar"
  CONFIG_GIT_PASSWORD: ""

  JWT_SECRET: ""
  CONFIG_SERVER_PASSWORD: ""
  KEYCLOAK_CLIENT_SECRET: ""
  MAIL_PASSWORD: ""
