# --- Eureka Server Application Configuration (K8s) ---

server:
  port: 8761

spring:
  application:
    name: eurekaserver

# ----------------------------------------------------
# EUREKA SERVER CONFIGURATION
# ----------------------------------------------------
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

# ----------------------------------------------------
# ACTUATOR (HEALTH CHECK) CONFIGURATION
# ----------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

# ----------------------------------------------------
# LOGGING CONFIGURATION
# ----------------------------------------------------
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
