spring:
  application:
    name: userassessmentservice

  datasource:
    url: ${DB_URL_ASSESSMENT}
    username: ${DB_USERNAME_ASSESSMENT}
    password: ${DB_PASSWORD_ASSESSMENT}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cms-realm

server:
  port: 0

eureka:
  instance:
    hostname: userassessmentservice
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
